name: miru_app
description: A new Flutter project.
publish_to: "none"
version: 1.5.2+17

environment:
  sdk: ">=3.0.3 <4.0.0"

dependencies:
  cached_network_image: ^3.2.3
  desktop_multi_window: ^0.2.0
  dio: ^5.2.1+1
  easy_refresh: ^3.3.2+1
  fluent_ui: ^4.6.2
  flutter:
    sdk: flutter
  flutter_animate: ^4.1.1+1
  flutter_code_editor: ^0.3.0
  flutter_highlight: ^0.7.0
  flutter_i18n: ^0.33.0
  flutter_js: ^0.7.2
  flutter_markdown: ^0.6.16
  get: ^4.6.5
  go_router: ^10.0.0
  highlight: ^0.7.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  json_annotation: ^4.8.1
  media_kit: ^1.1.1
  media_kit_libs_android_video: ^1.1.1
  media_kit_libs_linux: ^1.0.2
  media_kit_libs_macos_video: ^1.0.5
  media_kit_libs_windows_video: ^1.0.2
  media_kit_native_event_loop: ^1.0.4
  media_kit_video: ^1.0.2
  package_info_plus: ^4.0.2
  palette_generator: ^0.3.3+2
  path: ^1.8.3
  path_provider: ^2.0.15
  screenshot: ^2.1.0
  scrollable_positioned_list: ^0.3.8
  url_launcher: ^6.1.11
  window_manager: ^0.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  isar_generator: ^3.1.0+1
  build_runner: ^2.4.5
  json_serializable: ^6.7.0

flutter:
  uses-material-design: true
  assets:
    - assets/i18n/
    - assets/icon/logo.png
